### ISSUE TITLE
MRS 런처로 마인크래프트가 안들어가집니다.

### ISSUE THREAD

**Issue by ghost** [peunsu/MRSLauncher#1]
**100%까지는 뜨는데 마인크래프트가 안켜집니다.**

(사진 첨부)
![image](https://user-images.githubusercontent.com/71371309/102435224-97eb9d80-4059-11eb-8b1d-b7b1fc5841b4.png)

자바 연결은 했는데
유저 말고 Program Files에 받았거든요
그래서 문제일까요?

**Comment by peunsu** [comment]
@myounge2namur 
먼저 늦은 답변 죄송합니다.
런처 종료 후 재실행 해보셨나요?
정상적으로 실행되지 않는다면 답변 부탁드립니다.
일주일 이상 답변이 없으시면 이슈 닫겠습니다.
