### ISSUE TITLE
News, Directory_Path issue : 18_02_2024

### ISSUE THREAD

**Issue by JHyeok-Choi** [peunsu/MRSLauncher#7]
### NEWS Tab issue
* NEWS탭 선택시, 다시 시도 눌러도 해당 페이지를 나갔다 들어오기 3가지 전부 "뉴스 불러오기 실패" 메세지가 출력됩니다.
* 5분 ~ 10분정도 기다리니까 NEWS탭 내용들이 불러와졌고, 해당 오류를 재현하기 위해 런처를 끄고 켰지만 이때는 위처럼 에러가 생기지 않고 잘 로딩되었습니다.
* 최초 로딩에 시간이 어느정도 소요되고 그 이후에는 문제없는것 같습니다.

![NEWS_loading_fail](https://github.com/peunsu/MRSLauncher/assets/119499530/c5e5ee12-ab80-4d1f-824b-677041d6a3a2)

### Directory_Path_issue
* 이건 오류보다는 건의사항 입니다.
* 처음 런처 설치시 E 드라이브에 설치했지만, [설정 - 런처 - 데이터 디렉토리] 탭에 경로는 C로 되어있는데, 설치경로에 맞춰서 변경되게 바꿔주실 수 없으신가요?

![Main_Directory_Path](https://github.com/peunsu/MRSLauncher/assets/119499530/74040f41-c44d-4a14-9dd3-1a98b109aac6)

**Comment by peunsu** [comment]
의견 감사합니다.

1. 뉴스 관련해서는 해당 rss가 해외 서버에서 전송받는 방식이다보니 캐시에 저장되기까지 지연이 발생하는 것 같습니다. 타임아웃 시간 조정해보겠습니다.
2. 데이터 디렉토리 관련
  * 데이터 디렉토리는 런처 설치 위치와는 별개로, 기본값이 (윈도우의 경우) `%appdata%/.mrslauncher`로 설정되어 있으며, 런처 설치 위치에는 런처 데이터, 유저 설정 등이 저장됩니다. (마크 기본 런처와 유사하다고 보시면 됩니다)
  * 관습적으로 설정된 부분인데, 현재 상황을 생각해보면 굳이 `%appdata%`에 저장할 필요성이 없는 것 같아서 변경을 고려해보겠습니다. (MultiMC처럼 유저 데이터 저장 경로와 통합 시도 예정)

추가 제안 및 문의사항 있으시면 남겨주시고, 3일 비활성화 시 이슈 페이지 닫겠습니다.
